#!/bin/bash
########################################################################################
#
# Copyright by Stefan Koch <StefanKoch@gmx.org>, 2015
#
# This file is part of HP Office Jet 6500A scan fetcher (hpojet-fetcher)
#
#    hpojet-fetcher is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    hpojet-fetcher is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################################

if [ "$1" != "run" ]; then
	$0 run &
	exit 0
fi

# if anything goes wrong restart the fetcher
# reason: this will run unattended on headless system
while [ 1 ];
do
	/home/stefan/bin/scan-fetch.py
	sleep 15
done
